/**
 * Tests for the two pieces of logic living inside dashboard.html (repo root).
 *
 * WHY THESE ARE NOT IN src/
 *   dashboard.html is a standalone single-file tool, not part of the Next app. It has no
 *   build step and no imports, so the only way to test it is to pull the inline <script>
 *   out and run it. Keeping that under src/ would imply the app ships it.
 *
 * WHAT IS BEING PROTECTED
 *   1. The Org panel. Its data block is GENERATED by scripts/org-chart-sync.mjs, so these
 *      tests assert INVARIANTS, never specific counts -- pinning "Ananya sees 15" would
 *      turn a legitimate re-sync into a red suite, and a test that cries wolf gets
 *      deleted. What must always hold: every person renders, children nest under their
 *      parent, and the derived prose agrees with the numbers it was derived from.
 *   2. The save guard. dashboard.html rebuilds TASKS.md from only "## section" and
 *      "- [ ] task" lines, and autoSave fires 500ms after any change -- so without the
 *      guard, dragging one card deletes ~775 lines of this project's task history. That
 *      is the single most destructive thing in the file, so it gets a real test.
 *
 * The org module also carries the scar of a bug these tests now pin: a note derived from
 * ALL descendants produced "sabse zyada 19 tak pahunchta hai, 19 tak nahi" -- a sentence
 * that contradicts itself. `derived prose never contradicts itself` is that bug, frozen.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import vm from "node:vm";
import { describe, it, expect } from "vitest";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const DASHBOARD = join(ROOT, "dashboard.html");
const TASKS = join(ROOT, "TASKS.md");

interface OrgPerson {
  name: string;
  email: string;
  role: string;
  own: number;
  sees: number;
  children: OrgPerson[];
}
interface OrgNote {
  title: string;
  body: string;
}
interface TaskLoss {
  total: number;
  headings: number;
  tableRows: number;
  fences: number;
  other: number;
}

const escapeHtml = (t: unknown): string =>
  String(t).replace(/[&<>"']/g, (c) => {
    const map: Record<string, string> = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" };
    return map[c] ?? c;
  });

function inlineScript(): string {
  const html = readFileSync(DASHBOARD, "utf8");
  const match = html.match(/<script>([\s\S]*)<\/script>/);
  if (!match) throw new Error("dashboard.html has no inline <script> block");
  return match[1];
}

/** Slice one commented section out of the inline script, e.g. "ORG CHART". */
function section(name: string, until: string): string {
  const code = inlineScript();
  const from = code.indexOf(`// ===== ${name} =====`);
  const to = code.indexOf(`// ===== ${until} =====`);
  if (from < 0) throw new Error(`section "${name}" not found in dashboard.html`);
  if (to <= from) throw new Error(`section "${name}" is not followed by "${until}"`);
  return code.slice(from, to);
}

interface OrgRun {
  html: string;
  roots: OrgPerson[];
  peers: OrgPerson[];
  everyone: OrgPerson[];
  notes: OrgNote[];
  asOf: string;
  tenant: string;
  totalLeads: number;
  restrictedRoles: string[];
}

function runOrg(): OrgRun {
  let rendered = "";
  const ctx: Record<string, unknown> = {
    escapeHtml,
    document: {
      getElementById: (id: string) =>
        id === "orgContent"
          ? {
              set innerHTML(v: string) {
                rendered = v;
              },
            }
          : null,
    },
  };
  vm.createContext(ctx);
  vm.runInContext(section("ORG CHART", "TASKS FUNCTIONALITY") + "\nrenderOrg();", ctx);

  const read = <T,>(expr: string): T => vm.runInContext(expr, ctx) as T;
  const roots = read<OrgPerson[]>("ORG_ROOTS");
  const peers = read<OrgPerson[]>("ORG_PEERS");
  const flat = (list: OrgPerson[]): OrgPerson[] => list.flatMap((p) => [p, ...flat(p.children ?? [])]);

  return {
    html: rendered,
    roots,
    peers,
    everyone: flat([...roots, ...peers]),
    notes: read<OrgNote[]>("orgBuildNotes()"),
    asOf: read<string>("ORG_AS_OF"),
    tenant: read<string>("ORG_TENANT"),
    totalLeads: read<number>("ORG_TOTAL_LEADS"),
    restrictedRoles: read<string[]>("ORG_RESTRICTED_ROLES"),
  };
}

function runGuard(raw: string): { loss: TaskLoss | null; banner: string; bannerShown: boolean; saveLocked: boolean } {
  let banner = "";
  let display = "";
  let locked = false;
  const ctx: Record<string, unknown> = {
    escapeHtml,
    saveBtn: {
      set disabled(v: boolean) {
        locked = v;
      },
      set title(_v: string) {
        /* the guard sets a tooltip; irrelevant here */
      },
    },
    document: {
      getElementById: (id: string) =>
        id === "taskGuardBanner"
          ? {
              style: {
                set display(v: string) {
                  display = v;
                },
              },
              set innerHTML(v: string) {
                banner = v;
              },
            }
          : null,
    },
    RAW: raw,
  };
  vm.createContext(ctx);
  vm.runInContext(section("SAVE GUARD", "ORG CHART") + "\napplyTaskGuard(RAW);", ctx);
  return {
    loss: vm.runInContext("taskFileLoss", ctx) as TaskLoss | null,
    banner,
    bannerShown: display === "block",
    saveLocked: locked,
  };
}

/** Is `person` anywhere in `ancestor`'s subtree? */
function isUnder(ancestor: OrgPerson, person: OrgPerson): boolean {
  for (const child of ancestor.children ?? []) {
    if (child === person || isUnder(child, person)) return true;
  }
  return false;
}

describe("dashboard.html — Org panel", () => {
  const org = runOrg();

  it("keeps the markers scripts/org-chart-sync.mjs writes between", () => {
    const html = readFileSync(DASHBOARD, "utf8");
    expect(html).toContain(">>> ORG DATA");
    expect(html).toContain("<<< ORG DATA");
    expect(html.indexOf(">>> ORG DATA")).toBeLessThan(html.indexOf("<<< ORG DATA"));
  });

  it("carries a date and a tenant, because a number without either is not a measurement", () => {
    expect(org.asOf).toMatch(/\d{1,2} \w{3} \d{4}/);
    expect(org.tenant.trim().length).toBeGreaterThan(0);
    expect(org.totalLeads).toBeGreaterThanOrEqual(0);
  });

  it("holds one well-formed record per person, with no duplicate email", () => {
    expect(org.everyone.length).toBeGreaterThan(0);
    for (const p of org.everyone) {
      expect(p.name.trim().length, `name for ${p.email}`).toBeGreaterThan(0);
      expect(p.email).toMatch(/@/);
      expect(p.role.trim().length, `role for ${p.email}`).toBeGreaterThan(0);
      expect(Number.isInteger(p.own), `own for ${p.email}`).toBe(true);
      expect(Number.isInteger(p.sees), `sees for ${p.email}`).toBe(true);
      expect(p.own).toBeGreaterThanOrEqual(0);
      expect(p.sees).toBeGreaterThanOrEqual(0);
    }
    const emails = org.everyone.map((p) => p.email);
    expect(new Set(emails).size).toBe(emails.length);
  });

  it("never claims someone owns or sees more than the tenant has", () => {
    const owned = org.everyone.reduce((n, p) => n + p.own, 0);
    expect(owned).toBeLessThanOrEqual(org.totalLeads);
    for (const p of org.everyone) {
      expect(p.sees, `${p.email} sees more leads than exist`).toBeLessThanOrEqual(org.totalLeads);
    }
  });

  it("puts the peers in ORG_PEERS only when they really have nobody under them", () => {
    for (const p of org.peers) expect(p.children ?? []).toHaveLength(0);
    for (const r of org.roots) expect(r.children.length).toBeGreaterThan(0);
  });

  it("renders every person, with both numbers labelled separately", () => {
    for (const p of org.everyone) {
      expect(org.html, `${p.email} missing from the chart`).toContain(escapeHtml(p.name));
      expect(org.html).toContain(escapeHtml(p.email));
    }
    const nodes = org.html.match(/class="org-node/g) ?? [];
    expect(nodes).toHaveLength(org.everyone.length);
    /* Both columns exist for every node -- the whole point is that they are not one
       number. Matched as markup, not as words: the notes below the chart talk about
       "apne leads" in prose too, and a bare text count picks those up. */
    expect((org.html.match(/<span>apne leads<\/span>/g) ?? []).length).toBe(org.everyone.length);
    expect((org.html.match(/<span>dikhte hain<\/span>/g) ?? []).length).toBe(org.everyone.length);
  });

  it("nests each child after its own parent", () => {
    const at = (p: OrgPerson): number => org.html.indexOf(escapeHtml(p.email));
    const check = (parent: OrgPerson): void => {
      for (const child of parent.children ?? []) {
        expect(at(child), `${child.email} should render inside ${parent.email}`).toBeGreaterThan(at(parent));
        check(child);
      }
    };
    for (const r of org.roots) check(r);
  });

  it("shows the as-of badge and the read-only verify command", () => {
    expect(org.html).toContain(escapeHtml(org.asOf));
    expect(org.html).toContain("verify-reporting-lines.sql");
  });

  it("derives the partition note's arithmetic instead of stating it", () => {
    const note = org.notes.find((n) => /jodne layak/.test(n.title));
    expect(note, "the two-numbers note is missing").toBeDefined();
    const sum = org.everyone.reduce((n, p) => n + p.own, 0);
    const shown = note?.body.match(/(\d+(?: \+ \d+)*) = (\d+)/);
    expect(shown, `no "a + b = c" in: ${note?.body}`).not.toBeNull();
    if (!shown) return;
    const parts = shown[1].split(" + ").map(Number);
    expect(parts.reduce((a, b) => a + b, 0)).toBe(Number(shown[2]));
    expect(Number(shown[2])).toBe(sum);
  });

  it("derived prose never contradicts itself", () => {
    for (const note of org.notes) {
      const pair = note.body.match(/(\d+) tak pahunchta hai, (\d+) tak nahi/);
      if (!pair) continue;
      expect(Number(pair[1]), `contradiction in "${note.title}"`).not.toBe(Number(pair[2]));
      expect(Number(pair[1])).toBeLessThan(Number(pair[2]));
    }
  });

  it("says so whenever a root is holding leads back from the people it governs", () => {
    /* This is the real pin for the bug above, and the check that came second.
       Asserting "no self-contradicting sentence" was not enough: counting ALL descendants
       instead of the restricted ones makes the highest count equal the total, which trips
       the note's own skip condition -- so the wrong version does not contradict itself, it
       goes SILENT. A missing note is invisible to a test that only inspects the notes
       present. So this states the invariant from the data instead: if a root owns leads and
       someone it actually restricts sees fewer than all of them, the panel must say so, and
       must quote the highest figure among exactly those people. */
    for (const root of org.roots) {
      const governed = org.everyone.filter(
        (p) => p !== root && org.restrictedRoles.includes(p.role) && isUnder(root, p),
      );
      const highest = governed.reduce((m, p) => Math.max(m, p.sees), 0);
      const shouldExist = root.own > 0 && governed.length > 0 && highest < org.totalLeads;
      const note = org.notes.find((n) => n.title.includes("apne leads neeche kabhi nahi jaate") && n.body.includes(root.name));

      if (!shouldExist) continue;
      expect(note, `${root.email} withholds ${root.own} lead(s) from its team and the panel is silent`).toBeDefined();
      expect(note?.body, `the note must quote ${highest}, the most any restricted person below sees`).toContain(
        `${highest} tak pahunchta hai`,
      );
    }
  });

  it("only claims a manager gains nothing when that is actually true of them", () => {
    const claimed = org.notes.filter((n) => /Manager hone se/.test(n.title));
    const actually = org.everyone.filter((p) => (p.children ?? []).length > 0 && p.sees === p.own);
    expect(claimed).toHaveLength(actually.length);
    for (const p of actually) {
      expect(claimed.some((n) => n.body.includes(p.name))).toBe(true);
    }
  });

  it("only calls a role unrestricted if ORG_RESTRICTED_ROLES agrees", () => {
    const note = org.notes.find((n) => /rok hai hi nahi/.test(n.title));
    if (!note) return; // legitimately absent when everyone is restricted
    const named = org.everyone.filter((p) => note.body.includes(p.name.split(" ")[0]));
    expect(named.length).toBeGreaterThan(0);
    for (const p of named) {
      expect(org.restrictedRoles, `${p.email} is restricted but named as free`).not.toContain(p.role);
      expect(p.sees).toBe(org.totalLeads);
    }
  });
});

describe("dashboard.html — save guard", () => {
  /* Independent recount, so the test does not simply agree with the code under test:
     a line survives dashboard.html's round trip only if it is "# Tasks", a "## " section,
     or a "- [ ] " task. Everything else is a line saving would delete. */
  const wouldBeLost = (raw: string): number =>
    raw
      .split(/\r?\n/)
      .map((l) => l.trim())
      .filter((t) => t.length > 0)
      .filter((t) => t !== "# Tasks" && !/^##\s/.test(t) && !/^-\s\[[ xX]\]/.test(t)).length;

  it("locks saving on this project's real TASKS.md, and says how much was at stake", () => {
    const raw = readFileSync(TASKS, "utf8");
    const { loss, banner, bannerShown, saveLocked } = runGuard(raw);

    expect(loss).not.toBeNull();
    expect(saveLocked).toBe(true);
    expect(bannerShown).toBe(true);
    expect(loss?.total).toBe(wouldBeLost(raw));
    // The number has to be IN the banner: "save is off" without it reads as a glitch.
    expect(banner).toContain(String(loss?.total));
    expect(loss?.headings).toBeGreaterThan(0);
  });

  it("leaves a plain board-shaped file fully editable", () => {
    const simple = ["# Tasks", "", "## Active", "- [ ] **Write docs** - later", "  - [x] outline", "", "## Done", "- [x] **Ship it**", ""].join("\n");
    const { loss, bannerShown, saveLocked } = runGuard(simple);
    expect(loss).toBeNull();
    expect(bannerShown).toBe(false);
    expect(saveLocked).toBe(false);
  });

  it("still locks for an h1 other than \"# Tasks\", because that one really is dropped", () => {
    // toMarkdown() always writes the literal "# Tasks", so any other title is lost.
    const { loss, saveLocked } = runGuard("# My own title\n\n## Active\n- [ ] **x**\n");
    expect(loss?.total).toBe(1);
    expect(saveLocked).toBe(true);
  });

  it("counts what it would delete by kind, not just in total", () => {
    const raw = ["# Tasks", "## Active", "### A section", "prose line", "| a | b |", "|---|---|", "```", "code", "```", "- [ ] **kept**"].join("\n");
    const { loss } = runGuard(raw);
    expect(loss?.headings).toBe(1);
    expect(loss?.tableRows).toBe(2);
    expect(loss?.fences).toBe(2);
    expect(loss?.other).toBe(2); // the prose line and the line inside the fence
    expect(loss?.total).toBe(wouldBeLost(raw));
  });
});
