// @vitest-environment jsdom
import { describe, it, expect, afterEach } from "vitest";
import { render, cleanup } from "@testing-library/react";
import { AiPerformancePanel } from "./ai-performance-card";
import { aiConversion, aiFunnel, aiRevenue, topObjections } from "@/lib/ai/performance";
import type { AiPerformance } from "@/lib/ai/performance.server";

afterEach(cleanup);

/** The state the live data is actually in: things drafted, nothing ever sent. */
const asItIsToday = (): AiPerformance => ({
  funnel: aiFunnel([
    ...Array.from({ length: 19 }, () => ({
      action: "reply.send",
      outcome: "held",
      reason: "the reply is safe to send, but replies are set to hold for this workspace",
      createdAt: "2026-08-24T10:00:00Z",
    })),
    ...Array.from({ length: 9 }, () => ({
      action: "reply.send",
      outcome: "failed",
      reason: "The AI did not answer, and gave no reason.",
      createdAt: "2026-08-24T10:00:00Z",
    })),
    ...Array.from({ length: 2 }, () => ({
      action: "quote.send",
      outcome: "skipped",
      reason: "a person switched ALL automation off for this workspace",
      createdAt: "2026-08-23T10:00:00Z",
    })),
  ]),
  conversion: aiConversion({ leadsReached: 0, leadsConverted: 0 }),
  revenue: aiRevenue({ paidRupees: 0, sentCount: 0 }),
  objections: topObjections(Array.from({ length: 15 }, () => "Zoho is cheaper than this")),
  unavailable: false,
});

const working = (): AiPerformance => ({
  funnel: aiFunnel([
    { action: "reply.send", outcome: "sent", reason: null, createdAt: "2026-08-24T10:00:00Z" },
    { action: "reply.send", outcome: "sent", reason: null, createdAt: "2026-08-24T11:00:00Z" },
  ]),
  conversion: aiConversion({ leadsReached: 20, leadsConverted: 5 }),
  revenue: aiRevenue({ paidRupees: 490644, sentCount: 2 }),
  objections: topObjections([
    ...Array.from({ length: 14 }, () => "Zoho is cheaper"),
    ...Array.from({ length: 11 }, () => "too expensive for our budget"),
  ]),
  unavailable: false,
});

describe("with the data as it actually is — drafted plenty, sent nothing", () => {
  const html = () =>
    render(<AiPerformancePanel data={asItIsToday()} windowDays={90} />).container.textContent ?? "";

  it("shows an em dash for conversion, never 0%", () => {
    /* "0%" and "never allowed to try" send somebody to fix two different things. The first is a
       prompt problem; the truth is a dial. */
    const text = html();
    expect(text).not.toContain("0%");
    expect(text).toContain("has not sent a message to a customer yet");
  });

  it("shows no rupee figure at all rather than ₹0", () => {
    /* ₹0 reads as "the AI earned nothing", which invites the conclusion that it does not work.
       The truth is that nothing it wrote has ever left the building. */
    expect(html()).not.toMatch(/₹\s*0\b/);
  });

  it("leads with the block reason, in the log's own words", () => {
    /* The one actionable number on the panel today. */
    const text = html();
    expect(text).toContain("What is in the way most often");
    expect(text).toContain("replies are set to hold for this workspace");
  });

  it("separates a deliberate switch-off from an obstacle", () => {
    expect(html()).toContain("a deliberate no, not a problem");
  });

  it("refuses to rank objections on fifteen messages, and says how many it needs", () => {
    const text = html();
    expect(text).toContain("Only 15 customer messages");
    expect(text).toContain("25");
    expect(text).not.toContain("Zoho");
  });

  it("names the window rather than implying 'ever'", () => {
    expect(html()).toContain("Last 90 days");
  });
});

describe("once messages are actually going out", () => {
  const html = () =>
    render(<AiPerformancePanel data={working()} windowDays={90} />).container.textContent ?? "";

  it("shows the rate WITH both halves of it", () => {
    /* A rate on its own is a number to believe; a rate next to "5 paid of 20" is a number to
       check. */
    const text = html();
    expect(text).toContain("25%");
    expect(text).toContain("5 paid of 20 leads the AI wrote to");
  });

  it("says 'touched' and 'association, not credit', never 'generated'", () => {
    /* The brief asked for "Revenue Generated by AI". The AI drafts, a person reviews, the
       customer decides — attributing the rupees to one of the three is a choice, not a
       measurement, so the label is the guard. */
    const text = html();
    expect(text).toContain("Revenue on deals it touched");
    expect(text).toContain("association, not credit");
    expect(text).not.toMatch(/generated/i);
  });

  it("puts the send count next to the money", () => {
    expect(html()).toContain("2 AI messages reached the customer");
  });

  it("ranks objections once the sample is big enough, with the sample size shown", () => {
    const text = html();
    expect(text).toContain("Zoho");
    expect(text).toContain("of 25 customer");
    expect(text).toContain("one message can raise two");
  });

  it("shows no block panel when nothing is being blocked", () => {
    expect(html()).not.toContain("What is in the way most often");
  });
});

describe("the two states that must not look like zero", () => {
  it("says it could not read, rather than showing an empty funnel", () => {
    const data: AiPerformance = { ...asItIsToday(), unavailable: true };
    const text = render(<AiPerformancePanel data={data} windowDays={90} />).container.textContent ?? "";
    expect(text).toContain("not the same as no activity");
  });

  it("says the AI has handled nothing, rather than showing four zeroes", () => {
    const data: AiPerformance = {
      funnel: aiFunnel([]),
      conversion: aiConversion({ leadsReached: 0, leadsConverted: 0 }),
      revenue: aiRevenue({ paidRupees: 0, sentCount: 0 }),
      objections: topObjections([]),
      unavailable: false,
    };
    const text = render(<AiPerformancePanel data={data} windowDays={90} />).container.textContent ?? "";
    expect(text).toContain("has not handled anything in the last 90 days");
  });
});
