/**
 * /quote/view/[token] — the token-only quote link.
 *
 * ─── WHY THIS IS A LOOKUP AND NOT A SECOND QUOTE PAGE ───────────────────────
 * The customer-facing quote page already exists at /quote/[id]/accept?t=<token>, with
 * its own token check, its own cost-stripping projection, its own view tracking and its
 * own Razorpay gate. Building a second page at this URL would mean two implementations
 * of the SECURITY model — which is the one place in a codebase where two copies is not
 * a maintenance cost but a vulnerability, because only one of them gets fixed.
 *
 * This codebase has already paid for that lesson three times over with duplicated rule
 * tables (three product price lists, two UserRole unions). Security is where it would
 * cost the most.
 *
 * So this route resolves the token to a quote and redirects to the canonical page. The
 * shorter URL exists, and there is still exactly one page.
 *
 * ─── THE TOKEN IS THE ONLY CREDENTIAL, SO THE LOOKUP IS THE GUARD ───────────
 * A miss and a wrong token both render notFound(), identically — anything else lets
 * someone learn whether a token is real by watching how the server behaves.
 */
import { notFound, redirect } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Your quote",
  robots: "noindex",
};

export default async function QuoteByTokenPage({ params }: { params: { token: string } }) {
  const token = (params.token ?? "").trim();
  /* Bail before touching the database on anything that cannot be a token. Tokens are
     generated by the app; a short or oversized value is a probe, not a typo. */
  if (token.length < 16 || token.length > 128) notFound();

  const supabase = createAdminClient();
  const { data: quote } = await supabase
    .from("quotes")
    .select("id, status")
    .eq("public_token", token)
    .maybeSingle();

  // Same answer for "no such token" and "that quote is still a draft".
  if (!quote || quote.status === "draft") notFound();

  redirect(`/quote/${quote.id}/accept?t=${encodeURIComponent(token)}`);
}
