import { describe, it, expect } from "vitest";
import {
  MIN_MESSAGES_FOR_OBJECTIONS,
  aiConversion,
  aiFunnel,
  aiRevenue,
  topObjections,
  type AiActionRow,
} from "./performance";

const row = (over: Partial<AiActionRow> = {}): AiActionRow => ({
  action: "reply.send",
  outcome: "held",
  reason: "replies are set to hold for this workspace",
  createdAt: "2026-08-24T10:00:00Z",
  ...over,
});

/* ══ ZERO SENDS MEANS null, NOT 0% ═══════════════════════════════════════════
   The measurement this whole module was shaped by: the live ai_action_log has 34 rows and NOT
   ONE with outcome `sent`. Every metric the brief asked for has an empty numerator today. */

describe("a metric with no data says so, instead of saying zero", () => {
  it("returns a null conversion rate when nothing has ever been sent", () => {
    /* "0%" and "never allowed to try" have OPPOSITE fixes. The first sends somebody to look at
       prompts; the truth is a dial, or an unverified sending domain. A number that points at
       the wrong repair is worse than no number. */
    const c = aiConversion({ leadsReached: 0, leadsConverted: 0 });
    expect(c.rate).toBeNull();
    expect(c.unavailable).toContain("has not sent a message to a customer yet");
    expect(c.unavailable).toContain("not a low score");
  });

  it("returns null revenue when nothing has ever been sent", () => {
    const r = aiRevenue({ paidRupees: 490644, sentCount: 0 });
    expect(r.touchedRupees).toBeNull();
    expect(r.unavailable).toContain("this team's own work with the AI's name on it");
  });

  it("refuses to rank objections on a handful of messages", () => {
    /* The live table holds FIFTEEN customer turns, so this is not theoretical. Three objections
       out of eleven messages is four people, not a finding. */
    const s = topObjections(Array.from({ length: 15 }, () => "Zoho is cheaper than this"));
    expect(s.top).toEqual([]);
    expect(s.messagesRead).toBe(15);
    expect(s.unavailable).toContain("Only 15 customer messages");
    expect(s.unavailable).toContain("decision made on noise");
  });

  it("still reports the counts it DOES have while withholding the ranking", () => {
    /* Withholding a conclusion is not the same as withholding the data. The sample size is the
       actionable number here — it tells Pardeep to wait rather than to act. */
    const s = topObjections(["Zoho is cheaper", "too expensive", "hello"]);
    expect(s.messagesRead).toBe(3);
    expect(s.messagesWithObjection).toBe(2);
  });
});

/* ══ Once there IS data ══════════════════════════════════════════════════════ */

describe("aiConversion", () => {
  it("computes the rate and shows both halves of it", () => {
    const c = aiConversion({ leadsReached: 20, leadsConverted: 5 });
    expect(c.rate).toBe(0.25);
    expect(c.reached).toBe(20);
    expect(c.converted).toBe(5);
    expect(c.unavailable).toBe("");
  });

  it("clamps a converted count above the reached count", () => {
    /* Rather than trusting it. A rate above 100% on a founder's dashboard would come from a SQL
       query two files away where nothing checks the relationship between the two numbers. */
    const c = aiConversion({ leadsReached: 10, leadsConverted: 14 });
    expect(c.rate).toBe(1);
    expect(c.converted).toBe(10);
  });

  it("refuses negative and fractional inputs rather than propagating them", () => {
    expect(aiConversion({ leadsReached: -5, leadsConverted: 2 }).rate).toBeNull();
    expect(aiConversion({ leadsReached: 10.7, leadsConverted: 3.9 }).reached).toBe(10);
  });
});

describe("aiRevenue", () => {
  it("reports whole rupees and the send count together", () => {
    /* THE PAIRING IS THE POINT. A rupee figure on its own invites causation; the same figure
       next to "from 3 messages actually sent" cannot be misread as the AI having earned it. */
    const r = aiRevenue({ paidRupees: 490644, sentCount: 3 });
    expect(r.touchedRupees).toBe(490644);
    expect(r.sentCount).toBe(3);
  });

  it("is called TOUCHED, not generated, everywhere it is named", () => {
    /* The brief asked for "Revenue Generated by AI". There is no honest way to compute that —
       the AI drafts, a person reviews, the customer decides. The field name is the guard. */
    const r = aiRevenue({ paidRupees: 1000, sentCount: 1 });
    expect(Object.keys(r)).toContain("touchedRupees");
    expect(Object.keys(r).join(",")).not.toMatch(/generated/i);
  });

  it("rounds to whole rupees and never goes negative", () => {
    /* Money is stored in whole rupees here (AGENTS.md §1), not paise. */
    expect(aiRevenue({ paidRupees: 1234.6, sentCount: 1 }).touchedRupees).toBe(1235);
    expect(aiRevenue({ paidRupees: -50, sentCount: 1 }).touchedRupees).toBe(0);
  });
});

/* ══ The funnel, which is the honest headline today ══════════════════════════ */

describe("aiFunnel", () => {
  it("counts every outcome against the true denominator", () => {
    /* Shaped on the live distribution: 19 held, 8 failed, 4 held, 2 skipped, 1 failed. */
    const rows: AiActionRow[] = [
      ...Array.from({ length: 19 }, () => row({ outcome: "held" })),
      ...Array.from({ length: 9 }, () => row({ outcome: "failed", reason: "the AI did not answer" })),
      ...Array.from({ length: 2 }, () => row({ outcome: "skipped", reason: "automation off" })),
    ];
    const f = aiFunnel(rows);
    expect(f.drafted).toBe(30);
    expect(f.held).toBe(19);
    expect(f.failed).toBe(9);
    expect(f.skipped).toBe(2);
    expect(f.sent).toBe(0);
  });

  it("names the commonest block in the log's own words", () => {
    /* Not a category. logAiAction's reasons are written for a non-engineer (§24) — "no setting
       for this action, so its default hold applies" tells somebody to turn a dial, while a
       label like "policy" tells them to find an engineer. */
    const f = aiFunnel([
      row({ reason: "no setting for this action, so its default hold applies" }),
      row({ reason: "no setting for this action, so its default hold applies" }),
      row({ reason: "the agent was not confident enough" }),
    ]);
    expect(f.topBlock?.reason).toBe("no setting for this action, so its default hold applies");
    expect(f.topBlock?.count).toBe(2);
  });

  it("counts a failure as a block, because it also stopped a customer being answered", () => {
    /* From the customer's side a model that returned nothing and a dial set to hold are the
       same event: no reply arrived. Splitting them out of the block tally would make the "what
       is in the way" number smaller than what is actually in the way. */
    const f = aiFunnel([
      row({ outcome: "failed", reason: "the AI did not answer, and gave no reason" }),
      row({ outcome: "failed", reason: "the AI did not answer, and gave no reason" }),
      row({ outcome: "held", reason: "held once" }),
    ]);
    expect(f.topBlock?.reason).toContain("did not answer");
  });

  it("does not count a skip as a block", () => {
    /* A kill switch is a deliberate no, not an obstacle. Counting it would tell somebody to fix
       a decision they made on purpose. */
    const f = aiFunnel([row({ outcome: "skipped", reason: "a person switched automation off" })]);
    expect(f.topBlock).toBeNull();
    expect(f.skipped).toBe(1);
  });

  it("reports no block when everything went out", () => {
    const f = aiFunnel([row({ outcome: "sent", reason: null }), row({ outcome: "sent", reason: null })]);
    expect(f.sent).toBe(2);
    expect(f.topBlock).toBeNull();
  });

  it("ignores an empty or whitespace reason rather than ranking it", () => {
    const f = aiFunnel([row({ reason: "  " }), row({ reason: null }), row({ reason: "a real reason" })]);
    expect(f.topBlock?.reason).toBe("a real reason");
  });

  it("holds a stable order between two equally common blocks", () => {
    /* A tile that reshuffles on refresh without the data moving reads as a bug, and the person
       reading it stops trusting the rest of the panel. */
    const rows = [row({ reason: "bbb" }), row({ reason: "aaa" })];
    expect(aiFunnel(rows).topBlock?.reason).toBe("aaa");
    expect(aiFunnel([...rows].reverse()).topBlock?.reason).toBe("aaa");
  });

  it("survives an empty log", () => {
    const f = aiFunnel([]);
    expect(f.drafted).toBe(0);
    expect(f.topBlock).toBeNull();
  });
});

/* ══ Objections ══════════════════════════════════════════════════════════════ */

describe("topObjections", () => {
  /** Enough messages to clear the threshold, with a known distribution. */
  const sample = [
    ...Array.from({ length: 10 }, () => "Zoho is cheaper than what you quoted"),
    ...Array.from({ length: 6 }, () => "This is too expensive for our budget"),
    ...Array.from({ length: 3 }, () => "We will buy direct from Google"),
    ...Array.from({ length: 6 }, () => "Thanks, we need 30 seats on annual billing"),
  ];

  it("ranks by count, commonest first", () => {
    const s = topObjections(sample);
    expect(s.messagesRead).toBe(25);
    expect(s.top[0].count).toBeGreaterThanOrEqual(s.top[1].count);
    expect(s.top.map((t) => t.id)).toContain("cheaper_elsewhere");
    expect(s.top.map((t) => t.id)).toContain("too_expensive");
    expect(s.top.map((t) => t.id)).toContain("buy_direct");
  });

  it("uses the BATTLECARDS' taxonomy, not a second list of keywords", () => {
    /* `detectObjections` is the same function the prompt uses to pick which card to load, so
       what gets counted here and what gets answered there cannot drift. A separate reporting
       list would eventually rank an objection the agent has no card for. */
    const s = topObjections(sample);
    for (const t of s.top) {
      expect(t.label.length).toBeGreaterThan(0);
      expect(["cheaper_elsewhere", "buy_direct", "too_expensive", "thinking_about_it"]).toContain(t.id);
    }
  });

  it("counts one message under BOTH objections it raises", () => {
    /* "Zoho is cheaper and we'll buy direct" is two objections. Forcing it into one bucket
       would undercount the second every time it appears alongside the first — so the counts
       sum to more than messagesWithObjection, deliberately. */
    const messages = [
      ...Array.from({ length: 25 }, () => "Zoho is cheaper and we will buy direct from Google"),
    ];
    const s = topObjections(messages);
    expect(s.messagesWithObjection).toBe(25);
    const total = s.top.reduce((n, t) => n + t.count, 0);
    expect(total).toBeGreaterThan(s.messagesWithObjection);
  });

  it("shares are of the messages that objected, not of all messages", () => {
    /* Otherwise a quiet month of ordinary enquiries makes every objection look rare, and the
       one that IS costing deals gets ignored. */
    const s = topObjections(sample);
    const cheaper = s.top.find((t) => t.id === "cheaper_elsewhere");
    expect(cheaper).toBeDefined();
    expect(cheaper!.share).toBeGreaterThan(0.4);
  });

  it("counts nothing when nobody objected", () => {
    const s = topObjections(Array.from({ length: 30 }, () => "Please send the quotation."));
    expect(s.top).toEqual([]);
    expect(s.messagesWithObjection).toBe(0);
    expect(s.unavailable).toBe("");
  });

  it("holds a stable order between two equally common objections", () => {
    const messages = [
      ...Array.from({ length: 13 }, () => "too expensive"),
      ...Array.from({ length: 13 }, () => "we will buy direct"),
    ];
    const first = topObjections(messages).top.map((t) => t.id);
    const second = topObjections([...messages].reverse()).top.map((t) => t.id);
    expect(first).toEqual(second);
  });

  it("names the threshold in the message so somebody knows how long to wait", () => {
    const s = topObjections(["one message"]);
    expect(s.unavailable).toContain(String(MIN_MESSAGES_FOR_OBJECTIONS));
    expect(s.unavailable).toContain("1 customer message");
  });
});
